import type { Metadata } from "next";
import { Albert_Sans, Montserrat_Alternates } from "next/font/google"; 
import "./globals.css";
import Navbar from "./components/Navbar";

const albertSans = Albert_Sans({
  subsets: ['latin'],
  variable: '--font-albert-sans',
  display: 'swap',
});

const montserratAlt = Montserrat_Alternates({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat-alt',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${albertSans.variable} ${montserratAlt.variable} h-full antialiased`}
      
    >
      <body className={`${albertSans.className} min-h-full flex flex-col`}
     suppressHydrationWarning 
      >
        <div className="headerHeight pb-21.5"></div>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}